/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lv.lu.finalwork;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        AppTest classUnderTest = new AppTest();
        assertNotNull("app should have a greeting", classUnderTest.getClass());
    }
}
